name: cloud_toq_system
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get_storage:
  form_field_validator: ^1.1.0
  flutter_svg: ^1.1.3
  localize_and_translate: ^4.1.1
  datetime_picker_formfield: ^2.0.1
  introduction_screen: ^3.0.2
  pin_code_fields: ^7.4.0
  # anim_search_bar: ^2.0.2
  flutter_colorpicker: ^1.0.3
  intl: ^0.18.0
  flutter_slidable: ^3.0.0
  image_picker: ^0.8.5+3
  image_cropper: ^5.0.0

  enum_to_string: ^2.0.1
  http: ^1.0.0
  dio:
  shared_preferences: ^2.0.15
  mockito: ^5.3.0
  uuid: ^3.0.4
  equatable: ^2.0.3
  webview_flutter: ^3.0.4
  esc_pos_utils: ^1.1.0
  sunmi_printer_plus: ^2.1.01
#  webcontent_converter:
  # esc_pos_gen: ^3.2.0
  image: ^3.2.2
  date_format: ^2.0.6
  fluttertoast: ^8.2.1

  flutter_image_compress: ^1.1.3
  screenshot: ^1.2.3
  image_gallery_saver: ^1.7.1
  path_provider: ^2.0.4

  #state management  & structure
  provider: ^6.0.2

  #to display bottom sheet
  #  modal_bottom_sheet: ^2.0.1
  modal_bottom_sheet: ^3.0.0-pre
  native_pdf_renderer: ^5.0.0+1
  conditional_builder_null_safety:
  printer: ^0.0.5
  pdf: ^3.8.2
  open_file: ^3.1.0
  url_launcher: ^6.1.11
  flutter_barcode_listener: ^0.1.3
  visibility_detector: ^0.4.0+2
  flutter_staggered_grid_view: ^0.6.2
#  cached_network_image: ^3.2.3
  flutter_offline: ^2.1.0
  flutter_usb_printer:


dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/logo.png
    - assets/icons/
    - assets/images_used/
    - assets/images_used/print_logo.png
    - assets/images_used/side_menu_icons/
    - assets/images_used/double_arrow_down.png
    - assets/images_used/default_categories_img.png
    - assets/images_used/profit_img.png

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Medium.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts2/1.ttf
        - asset: assets/fonts2/2.ttf
        - asset: assets/fonts2/3.ttf
        - asset: assets/fonts2/4.ttf
        - asset: assets/fonts2/5.ttf
        - asset: assets/fonts2/6.ttf
